spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hchat?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    hikari:
      connection-timeout: 3000
# 以上为数据库连接池
hchat: tmpdir=D:/geihubStudy/fileupload  # 临时存放目录

fdfs:
  so-timeout: 1501
  connect-timeout: 3000
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 198.162.18.3:22122
  web-server-url: # web服务器的url
  pool:
    max-total: -1
    max-wait-millis: 5000
    max-total-per-key: 50
    max-idle-per-key: 10
    min-idle-per-key: 5

# 以上为fdfs配置
server:
  port: 8080
